#!/bin/sh
UDISK=$PWD
echo $UDISK
cp qt-5.5.0.tar.gz /.
cd /.
tar zxvf qt-5.5.0.tar.gz
cd -
cp ffmpeg-x264-arm.tar.gz /.
cd -
tar zxvf ffmpeg-x264-arm.tar.gz
cd -
cp etc.tar.gz /etc/

#back up
cd /etc
cp profile profile.bak
cp init.d/rcS init.d/rcS.bak

tar zxvf etc.tar.gz

#cd /udisk/1
cd $UDISK
cp -r service-robot usr_init restart_service audioPlayer configure.ini emotion/ /opt/

#cp video
cd /.
mkdir video
cd $UDISK
echo "copy videos...\n"
cp video/* /video/

cd /qt-5.5.0/
source /etc/profile
./dbus-uuidgen >/etc/machine-id

#done
echo -e "\ndone ! please reboot machine!" >/dev/tty
